name: Deploy CDK App

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # Required for GitHub OIDC to work
  contents: read        # Required for checking out the repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::403116234071:role/GitHub-CDKDeploy-DaycareManagement
          role-session-name: github-cdk-session
          aws-region: us-west-2  # or change to your region

      - name: Install dependencies
        run: npm install

      - name: Deploy CDK
        run: npx cdk deploy --app "node bin/infra.js" --require-approval never
